src/accounts/urls.py
from django.urls import path
from accounts.views import AccountRegistrationView, AccountLoginView, AccountLogoutView, AccountUpdateView, \
    AccountPasswordChangeView, AccountPasswordResetView, AccountPasswordResetDoneView, AccountPasswordResetConfirmView, \
    AccountPasswordResetCompleteView, AccountListView, AccountUpdateUserView

app_name = "accounts"

urlpatterns = [
    path('registration/', AccountRegistrationView.as_view(), name='registration'),
    path('login/', AccountLoginView.as_view(), name='login'),
    path('logout/', AccountLogoutView.as_view(), name='logout'),
    path('profile/', AccountUpdateView.as_view(), name='profile'),
    path('update/<int:user_id>', AccountUpdateUserView.as_view(), name='update'),
    path('password/', AccountPasswordChangeView.as_view(), name='password_change'),
    path('reset_password/', AccountPasswordResetView.as_view(),
         name='reset_password'),
    path('reset_password_sent/', AccountPasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>', AccountPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('reset_password_complete/', AccountPasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path('list/', AccountListView.as_view(), name='list'),

]

src/app/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from app.views import FirstPageView

urlpatterns = [
    path('', FirstPageView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('groups/', include('groups.urls')),
    path('lessons/', include('lessons.urls')),
    path('teachers/', include('teachers.urls')),
    path('students/', include('students.urls')),
    path('consultation/', include('consultations.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/teachers/urls.py
from django.urls import path

from teachers.views import TeacherDeleteView, TeacherCreateView, TeacherUpdateView, TeachersListView

app_name = 'teachers'

urlpatterns = [
    path('create/', TeacherCreateView.as_view(), name='create'),
    path('update/', TeacherUpdateView.as_view(), name='update'),
    path('delete/<int:teacher_id>', TeacherDeleteView.as_view(), name='delete'),
    path('list/', TeachersListView.as_view(), name='list'),
]

src/teachers/models.py
from django.db import models

# Create your models here.
from accounts.models import User
from consultations.models import Consultation
from core.mixins import FieldPermissionModelMixinV3
from groups.models import Group


class Teacher(FieldPermissionModelMixinV3,models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)

    # consultation = models.OneToOneField(
    #     to=Consultation,
    #     on_delete=models.CASCADE,
    #     null=True
    # )

    learn_groups = models.ManyToManyField(
        to=Group,
        related_name='teachers',
        null=True
    )

    academic_title = models.CharField(max_length=240, null=True, default="")
    academic_degree = models.CharField(max_length=240, null=True, default="")

    class Meta:
        permissions = (
            ('can_change_teacher_consultation', "Can change consultations"),
        )

    def full_name(self):
        return f'{self.user.last_name} {self.user.first_name}'

    def __str__(self):
        return f'{self.user.last_name} {self.user.first_name}'

src/teachers/forms.py
import django_filters
from django.forms import ModelForm

from accounts.models import User
from teachers.models import Teacher


class UserFilter(django_filters.FilterSet):
    class Meta:
        model = User
        fields = {
            'first_name': ['exact', 'icontains'],
            'last_name': ['exact', 'icontains'],
        }


class TeacherBaseForm(ModelForm):
    class Meta:
        model = Teacher
        fields = '__all__'


class TeacherCreateForm(TeacherBaseForm):
    pass


class TeacherUpdateForm(TeacherBaseForm):
    pass

src/teachers/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView, ListView

from accounts import roles
from teachers.forms import TeacherCreateForm, TeacherUpdateForm
from teachers.models import Teacher


class TeachersListView(LoginRequiredMixin, ListView, PermissionRequiredMixin):
    model = Teacher
    template_name = 'teachers/teachers-list.html'
    context_object_name = 'teachers'

    def get_object(self):
        teachers = Teacher.objects.all().values('user__id', 'user__first_name', 'user__last_name', 'user__surname',
                                                'user__email',
                                                'user__phone_number', 'academic_title','academic_degree')
        return teachers

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['teachers'] = self.get_object()
        context['role_id'] = roles.TEACHERS.id

        return context

    # def get(self, request, *args, **kwargs):
    #     teachers = Teacher.objects.all().values('user__first_name', 'user__last_name', 'user__surname', 'user__email',
    #                                             'user__phone_number')
    #
    #     return render(request,
    #                   template_name='teachers/teachers-list.html')


class TeacherCreateView(LoginRequiredMixin, CreateView, PermissionRequiredMixin):
    model = Teacher
    form_class = TeacherCreateForm
    template_name = 'teachers/teacher-create.html'
    success_url = reverse_lazy('index')


class TeacherUpdateView(LoginRequiredMixin, UpdateView, PermissionRequiredMixin):
    model = Teacher
    form_class = TeacherUpdateForm
    template_name = 'teachers/teacher-update.html'
    success_url = reverse_lazy('index')


class TeacherDeleteView(LoginRequiredMixin, DeleteView, PermissionRequiredMixin):
    model = Teacher
    template_name = 'teachers/teacher-delete.html'
    success_url = reverse_lazy('index')
    pk_url_kwarg = 'teacher_id'

src/teachers/templates/teachers/teacher-create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="Submit">
</form>
</body>
</html>

src/teachers/templates/teachers/teacher-delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="Submit">
</form>
</body>
</html>

src/teachers/templates/teachers/teacher-update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="Submit">
</form>
</body>
</html>

src/teachers/templates/teachers/teachers-list.html
{% extends 'base.html' %}
{% load static %}
{% load custom_tags %}

{% block menu %}
    {% include 'includes/sidebar.html' %}
{% endblock %}

{% block header %}
    {% include 'includes/header.html' %}
{% endblock %}

{% block content %}
<div class="shedule">
<h2 class="group__mainTitle">
    Викладачі кафедри
</h2>
<div class="group__teacher">
    <table class="group__table group__table--teacher">
        <tbody>
            <tr>
                <td class="group__week group__week--teacher">ПІБ</td>
                <td class="group__week group__week--teacher">Академічна посада</td>
                <td class="group__week group__week--teacher">Вчена ступінь</td>
                <td class="group__week group__week--teacher">Номер телефону</td>
                <td class="group__week group__week--teacher">Електронна пошта</td>
            </tr>
            {% for teacher in teachers %}
                <tr>
                    <td class="group__teacher--info">{{teacher.user__last_name}} {{teacher.user__first_name}} {{teacher.user__surname}}</td>
                    <td class="group__teacher--info">{{teacher.academic_title}}</td>
                    <td class="group__teacher--info">{{teacher.academic_degree}}</td>
                    <td class="group__teacher--info">{{teacher.user__phone_number}}</td>
                    <td class="group__teacher--info group__teacher--name">{{teacher.user__email}}<div class="group__teacher--delete" data-action="{% url 'teachers:delete' teacher_id=teacher.user__id %}"><img class="img-svg" src="{% static 'img/icon/delete.svg' %}" alt=""></div></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<div class="group__buttons">
    <div class="group__buttons--add">
        Додати викладача
    </div>
</div>
</div>
<div class="shedule__modal shedule__teacher">
<div class="shedule__modal--main">
    <div class="shedule__modal--close">
        <img class="img-svg" src="{% static 'img/icon/close.svg' %}" alt="">
    </div>
    <div class="shedule__modal--title">
        Додати нового викладача
    </div>
    <div class="shedule__modal--block">
        <div class="shedule__modal--item">
            <label for="">Пошук:</label>
            <input class="userSearch" type="text" name="" id="" placeholder="" data-action="{% url 'accounts:list' %}" data-role="{{role_id}}">
        </div>
<!--        <button class="shedule__modal&#45;&#45;btn">-->
<!--            Додати-->
<!--        </button>-->
    </div>
    <div class="search__block"></div>
    <div class="shedule__modal--cover"></div>
    <div class="cap__image--block">
        <img src="{% static 'img/icon/loading.svg' %}" alt="" class="cap__load img-svg">
    </div>
</div>

<div class="shedule__modal--check">
    <svg viewbox="0 0 48 48" xmlns="http://www.w3.org/2000/svg">
        <path d="M 18 32.34 l -8.34 -8.34 -2.83 2.83 11.17 11.17 24 -24 -2.83 -2.83 z" stroke="#fff" fill="transparent"/>
    </svg>
</div>
</div>
<div class="shedule__delete">
    <div class="shedule__modal--main">
        <div class="shedule__modal--title">
            Ви впевнені що хочете видалити викладача?
        </div>
        <div class="shedule__delete--buttons">
            <div class="shedule__delete--yes">
                Так
            </div>
            <div class="shedule__delete--no">
                Ні
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block scripts %}
    <script>
        var plus_src = "{% static 'img/icon/plusImg.png' %}"
    </script>
    <script src="{% static 'js/teacher-admin.js' %}"></script>
    <script src="{% static 'js/ajax-search-users.js' %}"></script>
    <script src="{% static 'js/user-update.js' %}"></script>
{% endblock %}