src/accounts/urls.py
from django.urls import path
from accounts.views import AccountRegistrationView, AccountLoginView, AccountLogoutView, AccountUpdateView, \
    AccountPasswordChangeView, AccountPasswordResetView, AccountPasswordResetDoneView, AccountPasswordResetConfirmView, \
    AccountPasswordResetCompleteView, AccountListView, AccountUpdateUserView

app_name = "accounts"

urlpatterns = [
    path('registration/', AccountRegistrationView.as_view(), name='registration'),
    path('login/', AccountLoginView.as_view(), name='login'),
    path('logout/', AccountLogoutView.as_view(), name='logout'),
    path('profile/', AccountUpdateView.as_view(), name='profile'),
    path('update/<int:user_id>', AccountUpdateUserView.as_view(), name='update'),
    path('password/', AccountPasswordChangeView.as_view(), name='password_change'),
    path('reset_password/', AccountPasswordResetView.as_view(),
         name='reset_password'),
    path('reset_password_sent/', AccountPasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>', AccountPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('reset_password_complete/', AccountPasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path('list/', AccountListView.as_view(), name='list'),

]

src/app/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from app.views import FirstPageView

urlpatterns = [
    path('', FirstPageView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('groups/', include('groups.urls')),
    path('lessons/', include('lessons.urls')),
    path('teachers/', include('teachers.urls')),
    path('students/', include('students.urls')),
    path('consultation/', include('consultations.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/groups/urls.py
from django.urls import path, include

from groups.views import StudentJournalView, SubjectStudentJournalView, StudentGroupView, StudentListView, \
    AdminModerateGroup, JournalSelectView, TeacherJournalUpdateView, AdminModerateStudentsGroup

app_name = 'groups'

urlpatterns = [
    path('<uuid:group_uuid>/', StudentGroupView.as_view(), name='group'),
    path('moderate/', StudentListView.as_view(), name='moderate'),
    path('moderate/<uuid:group_uuid>/schedule/', AdminModerateGroup.as_view(), name='moderate_group'),
    path('moderate/<uuid:group_uuid>/students/', AdminModerateStudentsGroup.as_view(), name='moderate_group_students'),
    path('<uuid:group_uuid>/schedule/', StudentJournalView.as_view(), name='group_schedule_for_student'),
    path('<uuid:group_uuid>/journal/', StudentJournalView.as_view(), name='group_schedule_for_student'),
    path('journal/', JournalSelectView.as_view(), name='select_journal'),
    path('journal/<uuid:group_uuid>/teacher/subject/<uuid:subject_uuid>/', TeacherJournalUpdateView.as_view(),
         name='group_journal_for_teacher'),
    path('journal/<uuid:group_uuid>/student/subject/<uuid:subject_uuid>/', SubjectStudentJournalView.as_view(),
         name='subject_journal_for_student'),

]

src/lessons/urls.py
from django.urls import path, include

from lessons.views import LessonCreateView, LessonUpdateView, LessonDeleteView, MarkUpdateView

app_name = 'lessons'

urlpatterns = [
    path('create/', LessonCreateView.as_view(), name='create'),
    path('update/<uuid:lesson_uuid>/', LessonUpdateView.as_view(), name='update'),
    path('delete/<uuid:lesson_uuid>/', LessonDeleteView.as_view(), name='delete'),
    path('mark/update/<int:mark_id>/', MarkUpdateView.as_view(), name='mark_update'),

]

src/students/urls.py
from django.urls import path

from students.views import StudentCreateView, StudentUpdateView, StudentDeleteView, StudentsListView

app_name = 'students'

urlpatterns = [
    path('create/', StudentCreateView.as_view(), name='create'),
    path('update/', StudentUpdateView.as_view(), name='update'),
    path('delete/<int:student_id>/', StudentDeleteView.as_view(), name='delete'),
    path('list/', StudentsListView.as_view(), name='list'),
]

src/groups/models.py
import datetime

from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models

# Create your models here.
from core.utils import generate_uuid
from lessons.models import Subject


class Group(models.Model):
    YEAR_CHOICES = [(r, r) for r in range(1918, datetime.date.today().year)]

    uuid = models.UUIDField(default=generate_uuid, db_index=True, unique=True)
    name = models.CharField(null=False, max_length=240)
    start_year = models.IntegerField(choices=YEAR_CHOICES)
    number = models.IntegerField(validators=[MinValueValidator(1), ], null=True, default=1)
    semester_weeks = models.IntegerField(validators=[MinValueValidator(10), MaxValueValidator(16)], default=15)

    subjects = models.ManyToManyField(
        to=Subject,
        related_name='groups',
    )

    headman = models.OneToOneField(
        to='accounts.User',
        on_delete=models.SET_NULL,
        null=True,
        related_name='headed_group'
    )

    def __str__(self):
        short_name = ""
        for temp_name in self.name.split(' '):
            short_name += temp_name[:1].upper()
        return f'{short_name}-{str(self.start_year)[2:]}{self.number}'

src/groups/forms.py
from django.core.exceptions import ValidationError
from django.forms import BaseInlineFormSet, ModelForm, ChoiceField

from accounts.models import User
from groups.models import Group
from lessons.models import Lesson

from collections import Counter


class LessonsInlineFormSet(BaseInlineFormSet):

    def clean(self):
        days = Lesson.DAYS_OF_WEEK
        time = Lesson.LESSON_TIME
        lessons = []
        subjects = []
        unique_lesson = []
        for lesson in self.cleaned_data:
            if [lesson['days'], lesson['time'], lesson['subject'], lesson['group']] not in unique_lesson:
                unique_lesson.append([lesson['days'], lesson['time'], lesson['subject'], lesson['group']])
                lessons.append([lesson['days'], lesson['time']])
                subjects.append(lesson['subject'])

        count_lessons_in_week = Counter(subjects)
        for item in count_lessons_in_week:
            if count_lessons_in_week[item] > 2:
                raise ValidationError(f'Занадто багато занятть з {item} на тиждень')
        # raise ValidationError(f'Колізія часу занятть.Виправіть час занятть з предмету {subject} у {day[1]} {time[1]}')
        unique_lesson_by_time = []
        for lesson in lessons:
            if lesson not in unique_lesson_by_time:
                unique_lesson_by_time.append(lesson)
            else:
                raise ValidationError(f'Колізія часу занятть.Виправіть час занятть у {days[lesson[0]][1]} {time[lesson[1]-1][1]}')


class GroupBaseForm(ModelForm):
    class Meta:
        model = Group
        fields = '__all__'


class GroupUpdateForm(GroupBaseForm):
    class Meta(GroupBaseForm.Meta):
        exclude = ['headman', 'uuid']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        students = [(st.user.id, st.full_name()) for st in self.instance.students.all()]
        self.fields['headman_field'] = ChoiceField(choices=students)
        self.fields['headman_field'].initial = [0]

    def save(self, commit=True):
        headman_id = self.cleaned_data['headman_field']
        self.instance.headman = User.objects.get(id=headman_id)
        return super().save(commit=True)

src/groups/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import render

# Create your views here.
from django.views.generic import DetailView, UpdateView, ListView

from accounts import roles
from groups.forms import GroupUpdateForm
from core.utils import get_journal_info
from groups.models import Group
from lessons.forms import LessonCreateForm
from lessons.models import Lesson, Mark
from lessons.utils import get_weeks_colspan


class StudentGroupView(PermissionRequiredMixin, LoginRequiredMixin, DetailView):
    permission_required = 'lessons.view_mark'
    model = Group
    pk_url_kwarg = 'group_uuid'
    template_name = 'groups/group-detail.html'
    context_object_name = 'group'

    def get_object(self):
        uuid = self.kwargs.get('group_uuid')
        return self.model.objects.get(uuid=uuid)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['students'] = self.get_object().students.select_related('group')

        return context


class StudentListView(PermissionRequiredMixin, LoginRequiredMixin, ListView):
    permission_required = 'group.view_group'
    model = Group
    template_name = 'groups/groups-list.html'
    context_object_name = 'groups'


class AdminModerateGroup(PermissionRequiredMixin, LoginRequiredMixin, UpdateView):
    permission_required = 'group.change_group'
    # model = Group
    # template_name = 'groups/group-moderate.html'
    # pk_url_kwarg = 'group_uuid'
    # form_class = GroupUpdateForm
    # success_url = reverse_lazy('groups:moderate')
    #
    # def get_object(self):
    #     uuid = self.kwargs.get('group_uuid')
    #     return self.model.objects.get(uuid=uuid)

    def get(self, request, group_uuid):
        group = Group.objects.get(uuid=group_uuid)
        lessons = group.lessons_group.distinct().select_related('teacher', 'subject', 'group').order_by('time', 'days')

        lessons_journal = get_journal_info(lessons)

        group_form = GroupUpdateForm(instance=group)
        lesson_create_form = LessonCreateForm(group_uuid=group_uuid)


        return render(
            request=request,
            template_name='groups/group-moderate.html',
            context={
                'group_form': group_form,
                'lesson_create_form': lesson_create_form,
                'lessons': lessons_journal,
                'group': group,
            }
        )


class AdminModerateStudentsGroup(PermissionRequiredMixin, LoginRequiredMixin, ListView):
    permission_required = 'group.change_group'

    def get(self, request, group_uuid, *args, **kwargs):
        group = Group.objects.get(uuid=group_uuid)
        students = group.students.all().values('user__id', 'user__first_name', 'user__last_name', 'user__surname',
                                               'user__email',
                                               'user__phone_number')
        role_id = roles.STUDENTS.id

        return render(
            request=request,
            template_name='groups/group-moderate-student.html',
            context={
                'students': students,
                'group': group,
                'role_id': role_id
            }
        )


class StudentJournalView(PermissionRequiredMixin, LoginRequiredMixin, DetailView):
    permission_required = 'lessons.view_mark'

    def get(self, request, group_uuid):
        group = Group.objects.get(uuid=group_uuid)

        subjects = group.subjects.select_related('teacher')

        all_lessons = group.lessons_group.distinct().select_related('group', 'subject', 'teacher').order_by('time',
                                                                                                            'days')

        lessons = get_journal_info(all_lessons)

        return render(
            request=request,
            template_name='groups/journal.html',
            context={
                'group': group,
                'lessons': lessons,
                'subjects': subjects,
            }
        )


class SubjectStudentJournalView(PermissionRequiredMixin, LoginRequiredMixin, UpdateView):
    permission_required = 'lessons.view_mark'

    def get(self, request, group_uuid, subject_uuid):
        group = Group.objects.get(uuid=group_uuid)
        groups = Group.objects.all()
        subject = group.subjects.get(uuid=subject_uuid)
        students = group.students.select_related('group').values('user', 'user__first_name', 'user__surname')
        lessons = group.lessons_group.filter(subject__uuid=subject_uuid).distinct()

        subjects = group.subjects.all()

        marks = list(Mark.objects.select_related('student', 'subject', 'group', 'lesson', 'teacher').filter(
            student__in=students.values('user'), subject__uuid=subject_uuid, group=group).order_by('lesson__mode',
                                                                                                   'week').values('id',
                                                                                                                  'points',
                                                                                                                  'student',
                                                                                                                  'lesson__mode'))

        colspan_weeks = get_weeks_colspan(lessons, group)

        return render(
            request=request,
            template_name='groups/journal-student-marks.html',
            context={
                'group': group,
                'groups': groups,
                'students': students,
                'lessons': lessons,
                'marks': marks,
                'subject': subject,
                'subjects': subjects,
                'colspan_weeks': colspan_weeks,

            }
        )


class JournalSelectView(PermissionRequiredMixin, LoginRequiredMixin, UpdateView):
    permission_required = 'lessons.view_mark'

    def get(self, request):

        subjects = []

        if self.request.user.is_teacher:
            lessons = Lesson.objects.filter(teacher=self.request.user).distinct()
            group_list = self.request.user.teacher.learn_groups.all()
        if self.request.user.is_student:
            lessons = Lesson.objects.filter(group=self.request.user.student.group).distinct()
            group_list = self.request.user.student.group

        for lesson in lessons:
            if lesson.subject not in subjects:
                subjects.append(lesson.subject)

        return render(
            request=request,
            template_name='groups/select-journal.html',
            context={
                'lessons': lessons,
                'subjects': subjects,
                'group_list': group_list,
            }
        )


class TeacherJournalUpdateView(PermissionRequiredMixin, LoginRequiredMixin, UpdateView):
    permission_required = 'lessons.change_mark'

    def get(self, request, group_uuid, subject_uuid):
        group = Group.objects.get(uuid=group_uuid)
        groups = self.request.user.teacher.learn_groups.all()
        students = group.students.select_related('group').values('user', 'user__first_name', 'user__last_name')
        lessons = group.lessons_group.filter(subject__uuid=subject_uuid, teacher=self.request.user).distinct()

        subjects = group.subjects.all().filter(lessons__teacher=self.request.user).distinct()

        marks = list(Mark.objects.select_related('student', 'subject', 'group', 'lesson', 'teacher').filter(
            student__in=students.values('user'), subject__uuid=subject_uuid, group=group,
            teacher=self.request.user).order_by('lesson__mode', 'week').values('id',
                                                                               'points',
                                                                               'student',
                                                                               'lesson__mode'))

        colspan_weeks = get_weeks_colspan(lessons, group)

        return render(
            request=request,
            template_name='groups/journal-teacher-marks.html',
            context={
                'group': group,
                'groups': groups,
                'students': students,
                'lessons': lessons,
                'marks': marks,
                'subjects': subjects,
                'colspan_weeks': colspan_weeks,
            }
        )

src/groups/templates/groups/group-detail.html
{% extends 'base.html' %}
{% load static %}

{% block menu %}
    {% include 'includes/sidebar.html' %}
{% endblock %}

{% block header %}
    {% include 'includes/header.html' %}
{% endblock %}

{% block content %}
                <div class="shedule">
                    <div class="shedule__nav">
                        <div class="shedule__semester">
                            Семестр: <span>2</span>
                        </div>
                        <a download="" href="#" class="shedule__download">
                            <img src="{% static 'img/icon/floppy-disk.svg' %}" class="floppy-disk" alt="">
                            <span>Завантажити розклад</span>
                        </a>
                    </div>
                    <div class="group__table">
                        <table>
                            <tr>
                                <th colspan="1" class="group__subtitle">
                                    №
                                </th>
                                <th rowspan="1" class="group__text group__title">ПІБ</th>
                            </tr>
                            {% for student in students %}
                            <tr>
                                <td class="group__student--info">
                                    <span>
                                        {{forloop.counter}}
                                    </span>
                                </td>
                                <td class="group__text {% if group.headman == student %}group__old{% endif %} ">
                                    <span>
                                        {{student}}
                                    </span>
                                </td>
                            </tr>
                            {% endfor %}
                        </table>
                    </div>
                </div>
{% endblock %}

src/groups/templates/groups/group-moderate-student.html
{% extends 'base.html' %}
{% load static %}
{% load custom_tags %}

{% block menu %}
    {% include 'includes/sidebar.html' %}
{% endblock %}

{% block header %}
    {% include 'includes/header.html' %}
{% endblock %}

{% block content %}
<div class="shedule">
<h2 class="group__mainTitle">
    Студенти групи {{group}}
</h2>
<div class="group__student">
    <table class="group__table group__table--teacher">
        <tbody>
            <tr>
                <td class="group__week group__week--teacher">ПІБ</td>
                <td class="group__week group__week--teacher">Номер телефону</td>
                <td class="group__week group__week--teacher">Електронна пошта</td>
            </tr>
            {% for student in students %}
                <tr>
                    <td class="group__student--info">{{student.user__last_name}} {{student.user__first_name}} {{student.user__surname}}</td>
                    <td class="group__student--info">{{student.user__phone_number}}</td>
                    <td class="group__student--info group__student--name">{{student.user__email}}<div class="group__teacher--delete" data-action="{% url 'students:delete' student_id=student.user__id %}"><img class="img-svg" src="{% static 'img/icon/delete.svg' %}" alt=""></div></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<div class="group__buttons">
    <div class="group__buttons--add">
        Додати студента
    </div>
</div>
</div>
<div class="shedule__modal shedule__teacher">
<div class="shedule__modal--main">
    <div class="shedule__modal--close">
        <img class="img-svg" src="{% static 'img/icon/close.svg' %}" alt="">
    </div>
    <div class="shedule__modal--title">
        Додати нового студента
    </div>
    <div class="shedule__modal--block">
        <div class="shedule__modal--item">
            <label for="">Пошук:</label>
            <input class="userSearch" type="text" name="" id="" placeholder="" data-action="{% url 'accounts:list' %}" data-role="{{role_id}}" data-group_uuid="{{group.uuid}}">
        </div>
<!--        <button class="shedule__modal&#45;&#45;btn">-->
<!--            Додати-->
<!--        </button>-->
    </div>
    <div class="search__block"></div>
    <div class="shedule__modal--cover"></div>
    <div class="cap__image--block">
        <img src="{% static 'img/icon/loading.svg' %}" alt="" class="cap__load img-svg">
    </div>
</div>

<div class="shedule__modal--check">
    <svg viewbox="0 0 48 48" xmlns="http://www.w3.org/2000/svg">
        <path d="M 18 32.34 l -8.34 -8.34 -2.83 2.83 11.17 11.17 24 -24 -2.83 -2.83 z" stroke="#fff" fill="transparent"/>
    </svg>
</div>
</div>
<div class="shedule__delete">
    <div class="shedule__modal--main">
        <div class="shedule__modal--title">
            Ви впевнені що хочете видалити студента?
        </div>
        <div class="shedule__delete--buttons">
            <div class="shedule__delete--yes">
                Так
            </div>
            <div class="shedule__delete--no">
                Ні
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block scripts %}
    <script>
        var plus_src = "{% static 'img/icon/plusImg.png' %}"
    </script>
    <script src="{% static 'js/teacher-admin.js' %}"></script>
    <script src="{% static 'js/ajax-search-users.js' %}"></script>
    <script src="{% static 'js/user-update.js' %}"></script>
{% endblock %}

src/groups/templates/groups/groups-list.html
{% extends 'base.html' %}
{% load static %}

{% block menu %}
    {% include 'includes/sidebar.html' %}
{% endblock %}

{% block header %}
    {% include 'includes/header.html' %}
{% endblock %}

{% block content %}
<div class="shedule">
                    <h2 class="group__mainTitle">
                        Групи кафедри
                    </h2>
                    <div class="group__teacher">
                        <table class="group__table group__table--teacher" id="create-lesson">
                            <tbody>
                                <tr>
                                    <td class="group__week group__week--teacher">Назва групи</td>
                                    <td class="group__week group__week--teacher">Розклад</td>
                                    <td class="group__week group__week--teacher">Студенти</td>
                                </tr>
                                {% for group in groups %}
                                    <tr>
                                        <td class="group__teacher--info">{{group}}</td>
                                        <td class="group__teacher--info"><a href="{% url 'groups:moderate_group' group_uuid=group.uuid %}">Редагувати розклад</a></td>
                                        <td class="group__teacher--info"><a href="{% url 'groups:moderate_group_students' group_uuid=group.uuid %}">Редагувати список студентів</a></td>
                                    </tr>
                                {% endfor %}

                            </tbody>
                        </table>
                    </div>
                </div>
{% endblock %}

src/groups/templates/groups/journal-teacher-marks.html
{% extends 'base.html' %}
{% load static %}
{% load custom_tags %}


{% block menu %}
    {% include 'includes/sidebar.html' %}
{% endblock %}

{% block header %}
    {% include 'includes/header.html' %}
{% endblock %}

{% block content %}
                <div class="shedule">
                    <div class="shedule__nav">
                        <div class="shedule__item">
                            <div class="shedule__item--semester">
                                Семестр: <span>2</span>
                            </div>
                                <div class="shedule__item--discipline">
                                    <span>
                                        Дисципліна:
                                    </span>
                                    <select class="" name="subject_name">
                                        {% for subject in subjects %}
                                            <option value="{{subject.uuid}}">
                                                {{subject}}
                                            </option>
                                        {% endfor %}
                                    </select>
                                </div>
                                <div class="shedule__item--group">
                                    <span>
                                        Група:
                                    </span>
                                    <select class="" name="group_name">
                                        {% for group in groups %}
                                        <option value="{{group.uuid}}">
                                            {{group}}
                                        </option>
                                        {% endfor %}
                                    </select>
                                </div>
                                <button class="shedule__item--btn shedule__item--openMarkBook">
                                    Відкрити
                                </button>
                            </form>
                        </div>

                        <a download="" href="#" class="shedule__download">
                            <img src="{% static 'img/icon/floppy-disk.svg' %}" class="floppy-disk" alt="">
                            <span>Завантажити журнал</span>
                        </a>
                    </div>

                    <div class="journal__table">
                        <table>
                            <tr>
                                <th rowspan="3" class="journal__text journal__title">ПІБ</th>
                                <th colspan="35" class="journal__subtitle">
                                    Тиждень
                                </th>
                            </tr>
                            <tr>
                                {% for week, week_colspan in colspan_weeks %}
                                    <th colspan="{{week_colspan}}" class="journal__week">
                                        {{week}}
                                    </th>
                                {% endfor %}
                                <th colspan="1" rowspan="2" class="journal__week journal__result">
                                    З
                                </th>
                            </tr>
                           {% for week in ''|get_range:group.semester_weeks %}
                                    {% for lesson in lessons %}
                                        {% if lesson.mode == 0 %}
                                            <td  class="journal__day">
                                                {{lesson.get_short_type}}.
                                            </td>
                                        {% elif lesson.mode == 1 and week|add:1|divisibleby:"2" %}
                                            <td  class="journal__day">
                                                {{lesson.get_short_type}}.
                                            </td>
                                        {% elif lesson.mode == 2 and not week|add:1|divisibleby:"2" %}
                                            <td  class="journal__day">
                                                {{lesson.get_short_type}}.
                                            </td>
                                        {% endif %}
                                    {% endfor %}
                            {% endfor %}
                            {% for student in students %}
                                <tr class="marks">
                                    <td class="journal__subject">
                                        <span>
                                           {{student.user__last_name}} {{student.user__first_name}}
                                        </span>
                                    </td>
                                    {% with res_point=0 %}
                                    {% for student_mark in marks %}
                                        {% if student_mark.student == student.user %}
                                            <td class="journal__mark">
                                                <input type="text" value="{% if student_mark.points %}{{student_mark.points}}{% endif %}" name="points" data-id="{{student.id}}" data-mark="{{student_mark.id}}" data-action="{% url 'lessons:mark_update' mark_id=student_mark.id %}">
                                            </td>
                                        {% endif %}
                                    {% endfor%}
                                    <td class="journal__result">
                                        {{res_point}}
                                    </td>
                                    {% endwith %}
                                </tr>
                            {% endfor %}
                        </table>
                        <div class="settings__save">
                            <button class="settings__btn" type="submit">
                                <img class="img-svg" src="{% static 'img/icon/floppy-disk.svg' %}" alt="">
                                Зберегти
                            </button>
                        </div>
                    </div>
                </div>
{% endblock %}
{% block scripts %}
    <script src="{% static 'js/select-journal.js' %}"></script>
    <script src="{% static 'js/journal-points-send.js' %}"></script>
{% endblock %}