src/accounts/urls.py
from django.urls import path
from accounts.views import AccountRegistrationView, AccountLoginView, AccountLogoutView, AccountUpdateView, \
    AccountPasswordChangeView, AccountPasswordResetView, AccountPasswordResetDoneView, AccountPasswordResetConfirmView, \
    AccountPasswordResetCompleteView, AccountListView, AccountUpdateUserView

app_name = "accounts"

urlpatterns = [
    path('registration/', AccountRegistrationView.as_view(), name='registration'),
    path('login/', AccountLoginView.as_view(), name='login'),
    path('logout/', AccountLogoutView.as_view(), name='logout'),
    path('profile/', AccountUpdateView.as_view(), name='profile'),
    path('update/<int:user_id>', AccountUpdateUserView.as_view(), name='update'),
    path('password/', AccountPasswordChangeView.as_view(), name='password_change'),
    path('reset_password/', AccountPasswordResetView.as_view(),
         name='reset_password'),
    path('reset_password_sent/', AccountPasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>', AccountPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('reset_password_complete/', AccountPasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path('list/', AccountListView.as_view(), name='list'),

]

src/app/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from app.views import FirstPageView

urlpatterns = [
    path('', FirstPageView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('groups/', include('groups.urls')),
    path('lessons/', include('lessons.urls')),
    path('teachers/', include('teachers.urls')),
    path('students/', include('students.urls')),
    path('consultation/', include('consultations.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/accounts/models.py
from PIL import Image
from django.db import models
from django.contrib.auth.models import AbstractUser

from accounts.validators import validate_phone_number


class User(AbstractUser):
    birth_date = models.DateField(null=True, blank=True)
    surname = models.CharField(max_length=210, blank=True)
    phone_number = models.CharField(null=True,
                                    max_length=20,
                                    validators=[validate_phone_number],
                                    default="+38(098)000-0000")
    image = models.ImageField(default='default.png', upload_to='accounts')
    is_student = models.BooleanField(default=False)
    is_teacher = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        image = Image.open(self.image)
        image.thumbnail((300, 300), Image.ANTIALIAS)
        image.save(self.image.path)

    def get_group_uuid(self):
        return self.student.group.uuid

    def in_group(self):
        return bool(self.student.group)

    def get_full_name(self):
        return f'{self.first_name} {self.last_name}'

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

src/accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm, AuthenticationForm, PasswordResetForm, \
    SetPasswordForm, PasswordChangeForm
from django.forms import ModelForm

from accounts.models import User
from accounts.utils import change_auth_group


class AccountRegistrationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'last_name', 'first_name']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'register__input',
            })


class AccountsChangePassword(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'reset__input reset__input--new',
                'required': 'True'
            })
        self.fields['old_password'].widget.attrs.update({
            'placeholder': 'Старий пароль',
        })
        self.fields['new_password1'].widget.attrs.update({
            'placeholder': 'Новий пароль',
        })
        self.fields['new_password2'].widget.attrs.update({
            'placeholder': 'Підтвердіть новий пароль',
        })


class UserChangeAdminForm(ModelForm):
    class Meta:
        fields = '__all__'

    def save(self, commit=True):
        user_role = self.cleaned_data['groups']
        change_auth_group(self.instance, user_role)
        return super().save(commit=False)


class AccountLoginForm(AuthenticationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'register__input'
            })


class AccountUpdateForm(UserChangeForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['surname', 'first_name', 'last_name', 'phone_number', 'username', 'email', 'image', 'is_teacher',
                  'is_student', 'groups']
        # fields = '__all__'

    def save(self, commit=True):
        user_role = self.cleaned_data['groups']
        change_auth_group(self.instance, user_role)
        return super().save(commit=True)


class AccountUpdateProfileForm(UserChangeForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['surname', 'first_name', 'last_name', 'phone_number', 'username', 'email', 'image']
        # fields = '__all__'

    def save(self, commit=True):
        if self.instance.is_teacher:
            self.instance.teacher.academic_title = self.cleaned_data['academic_title']
            self.instance.teacher.academic_degree = self.cleaned_data['academic_degree']
            self.instance.teacher.save()

        return super().save(commit=True)


class AccountAjaxUpdateForm(UserChangeForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['is_teacher', 'is_student', 'groups']
        # fields = '__all__'

    def clean(self):
        cleaned_data = super(AccountAjaxUpdateForm, self).clean()
        cleaned_data['group_uuid'] = self.data.get('group_uuid', '')
        return cleaned_data

    def save(self, commit=False):
        user_role = self.cleaned_data['groups']
        user_group_uuid = self.cleaned_data.get('group_uuid', '')
        change_auth_group(self.instance, user_role, user_group_uuid=user_group_uuid)

        return super().save(commit=True)


class ResetPasswordForm(PasswordResetForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].widget.attrs.update({
            'class': 'reset__input',
            'required': 'True',
            'placeholder': 'E-mail',
        })


class ResetPasswordConfirmForm(SetPasswordForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'reset__input reset__input--new',
                'required': 'True'
            })
        self.fields['new_password1'].widget.attrs.update({
            'placeholder': 'Новий пароль',
        })
        self.fields['new_password2'].widget.attrs.update({
            'placeholder': 'Підтвердіть новий пароль',
        })

src/accounts/views.py
import json

from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.db.models import Q
from django.http import HttpResponse, JsonResponse
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, ListView
from django.urls import reverse

from accounts.forms import AccountRegistrationForm, AccountLoginForm, ResetPasswordForm, \
    ResetPasswordConfirmForm, AccountAjaxUpdateForm, AccountUpdateProfileForm, AccountsChangePassword
from accounts.models import User


class AccountListView(PermissionRequiredMixin, LoginRequiredMixin, ListView):
    permission_required = 'lessons.create_mark'
    model = User

    def get(self, request, *args, **kwargs):
        if request.is_ajax():

            q = request.GET.get('term', '').capitalize()
            filter_set = Q()
            for item in q.split(' '):
                filter_set |= Q(first_name__icontains=item) | Q(last_name__icontains=item) | Q(surname__icontains=item)
            search_qs = User.objects.filter(filter_set, is_teacher = False, is_student = False, is_staff = False)[:6]
            # is_teacher = False, is_student = False, is_staff = False

            results = {}
            for i in range(len(search_qs)):
                results.update({f'{i}': {'full_name': search_qs[i].get_full_name(), 'id': search_qs[i].id}})

            data = json.dumps(results)
            mimetype = 'application/json'
            return HttpResponse(data, mimetype)


class AccountRegistrationView(CreateView):
    model = User
    template_name = 'registration.html'
    success_url = reverse_lazy('accounts:login')
    form_class = AccountRegistrationForm


class AccountLoginView(LoginView):
    template_name = 'login.html'
    form_class = AccountLoginForm

    def form_valid(self, form):
        remember = self.request.POST.get('remember-me', False)
        if not remember:
            self.request.session.set_expiry(0)
        return super().form_valid(form)


class AccountLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'logout.html'
    success_url = reverse_lazy('accounts:login')

    def get_redirect_url(self):
        return reverse('accounts:login')


class AccountUpdateUserView(PermissionRequiredMixin, LoginRequiredMixin, UpdateView):
    permission_required = 'lessons.create_mark'
    model = User
    pk_url_kwarg = 'user_id'
    form_class = AccountAjaxUpdateForm
    template_name = 'account-update.html'
    success_url = reverse_lazy('index')

    def post(self, request, user_id, *args, **kwargs):
        print(request.POST)
        user = User.objects.get(id=user_id)

        form = AccountAjaxUpdateForm(instance=user,
                                     data=request.POST)
        if form.is_valid():
            form.save()
        else:
            print(form.errors)
            return HttpResponse(status=500)

        data = {'name': user.get_full_name(), 'phone_number': user.phone_number, 'academic_degree': 'Доцент',
                'email': user.email, 'id': user.id}

        return JsonResponse(data)


class AccountUpdateView(LoginRequiredMixin,UpdateView):
    model = User
    template_name = 'profile.html'
    success_url = reverse_lazy('accounts:profile')
    form_class = AccountUpdateProfileForm

    def form_valid(self, form):
        form.cleaned_data['image'] = self.request.FILES.get('image')
        form.cleaned_data.update({'academic_title':self.request.POST.get('academic_title', '')})
        form.cleaned_data.update({'academic_degree':self.request.POST.get('academic_degree', '')})
        form.save()
        return super().form_valid(form)

    def get_object(self, queryset=None):
        return self.request.user


class AccountPasswordChangeView(PasswordChangeView):
    template_name = 'password-change.html'
    success_url = reverse_lazy('index')
    form_class = AccountsChangePassword


class AccountPasswordResetView(PasswordResetView):
    email_template_name = 'password_reset_email.html'
    html_email_template_name = 'password_reset_email.html'
    template_name = 'reset_password.html'
    success_url = reverse_lazy('accounts:password_reset_done')
    form_class = ResetPasswordForm


class AccountPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'password_reset_sent.html'
    success_url = reverse_lazy('accounts:password_reset_confirm')


class AccountPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'password_reset_form.html'
    success_url = reverse_lazy('index')
    form_class = ResetPasswordConfirmForm


class AccountPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'password_reset_form.html'
    success_url = reverse_lazy('accounts:profile')

src/accounts/templates/account-update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="Submit">
</form>
</body>
</html>

src/accounts/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
       <section class="register">
            <div class="register__block">
                <form class="register__form" method="post">
                    {% csrf_token %}
                    <div class="register__title">
                        Вхід
                    </div>
                    {{form.errors}}
                    <div class="register__item">
                        {{form.username.errors}}
                        {{form.username}}
                        <span class="register__focus">
                        </span>
                        <span class="register__item--title">
                            Логін
                        </span>
                    </div>
                    <div class="register__item">
                        {{form.password.errors}}
                        {{form.password}}
                        <span class="register__focus">
                        </span>
                        <span class="register__item--title">
                            Пароль
                        </span>
                    </div>
                    <div class="register__nav">
                        <div class="register__check">
                            <input class="register__inpCheckbox" id="ckb1" type="checkbox" name="remember-me" value="False">
                            <label class="register__lblCheckbox" for="ckb1">
                                <img src="{% static 'img/icon//check.svg' %}" class="img-svg" alt="">
                                Запам'ятати мене
                            </label>
                        </div>
                        <div class="register__forgot">
                            <a href="{% url 'accounts:reset_password' %}">
                                Забули пароль?
                            </a>
                        </div>
                    </div>
                    <button type="submit" class="register__btn">
                        Увійти
                    </button>
                    <div class="register__text">
                        У Вас немає аккаунту? <a href="{% url 'accounts:registration' %}">Зареєструватися</a>
                    </div>
                </form>
                {% include 'includes/captcha.html' %}
            </div>
       </section>
{% endblock %}

{% block scripts %}
    <script src="{% static 'js/auth2.js' %}"></script>
{% endblock %}

src/accounts/templates/logout.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="content">
        <div class="first-page__block">
            <img class="img-svg" src="{% static 'img/icon/first-svg.svg' %}" alt="">
            <h1 class="first-page__title">
                Вітаємо на сторінці нашої кафедри
            </h1>
            <h2 class="first-page__subtitle">
                Для початку користування усіма можливостями ресурсу, увійдіть у свій аккаунт
            </h2>
            <div class="first-page__buttons">
                <a class="first-page__btn" href="{% url 'accounts:login' %}">Увійти</a>
                <a class="first-page__btn" href="{% url 'accounts:registration' %}">Реєстрація</a>
            </div>
        </div>
    </div>
{% endblock %}

src/accounts/templates/password-change.html
{% extends 'base.html' %}
{% block content %}
{% load static %}


<div class="reset">
  <h1 class="reset__title title">Сторінка встановлення нового паролю</h1>
  <img src="{% static 'img/icon/reset-pass.svg' %}" class="reset__pass img-svg" alt="">

  <h3 class="reset__subtitle reset__subtitle--new subtitle">
    Створіть новий пароль
  </h3>
  <form action="" method="POST" class="reset__form reset__new">
    {% csrf_token %}
      {{form.old_password}}
      {{form.new_password1}}
      {{form.new_password2}}
    <input type="submit" class="reset__btn reset__btn--new" value="Надіслати" /><br>
  </form>
  <a class="reset__main reset__main--new" href="/">На головну</a>
</div>
{% endblock%}

src/accounts/templates/password_reset_done.html
{% extends 'base.html' %} 
{% block content%}
<div class="text-center" style="width: 80%; margin: 0 auto">
  <h1>Password reset complete</h1>
  <h6 style="width: 60%; margin: 0 auto">
    Your Password has been set. You may go ahead and login
  </h6>
</div>
<br />
<div class="text-center">
  <a href="{% url 'accounts:login' %}">Login</a>
</div>
{% endblock%}

src/accounts/templates/password_reset_email.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
	</head>
<body style="margin: 0; padding: 0; font-family: sans-serif;">
	<table align="center" cellpadding="0" cellspacing="0" width="600">
<!--		<tr>-->
<!--			<td align="center"  style="padding: 40px 0 30px 0;">-->
<!--				<img src="" alt="Зміна паролю" width="80%" height="auto" style="display: block;" />-->
<!--			</td>-->
<!--		</tr>-->
		<tr>
			<td width="260" valign="top" style="padding: 5px 20px 20px 20px; font-size: 36px; text-align: center;">
				Привіт {{ user.first_name }}!
			</td>
		</tr>
		<tr>
		 <td width="260" valign="top" style="padding: 10px 20px; font-size: 24px;">
			Ви запросили відновлення паролю облікового запису за адресою <a href="#">lms.ua</a>.
		 </td>
		</tr>
		<tr>
			<td width="260" valign="top" style="padding: 10px 20px; font-size: 18px;">
			   Перейдіть за посиланням нижче, для того щоб продовжити відновлення вашого паролю:
			</td>
		</tr>
		<tr>
			<td style="padding: 0px 20px;">
				<a href="{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}">{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}</a>
			</td>
		</tr>
		<tr>
			<td style="padding: 40px 20px 0px 20px">
				Якщо ви не виконували запит на відновлення паролю, видаліть це повідомлення, та напишіть до нашої технічної підтримки:
			</td>
		</tr>
		<tr>
			<td style="padding: 10px 20px 30px 20px">
				websamuraidev@gmail.com
			</td>
		</tr>
	   </table>
</body>
</html>

src/accounts/templates/password_reset_form.html
{% extends 'base.html' %}
{% block content %}
{% load static %}


<div class="reset">
  <h1 class="reset__title title">Сторінка встановлення нового паролю</h1>
  <img src="{% static 'img/icon/reset-pass.svg' %}" class="reset__pass img-svg" alt="">

  <h3 class="reset__subtitle reset__subtitle--new subtitle">
    Створіть новий пароль
  </h3>
  <form action="" method="POST" class="reset__form reset__new">
    {% csrf_token %}
    {{form.new_password1}}
    {{form.new_password2}}
    <input type="submit" class="reset__btn reset__btn--new" value="Надіслати" /><br>
  </form>
  <a class="reset__main reset__main--new" href="/">На головну</a>
</div>
{% endblock%}

src/accounts/templates/password_reset_sent.html
{% extends 'base.html' %}
{% block content %}
{% load static %}


<div class="reset">
  <h1 class="reset__title title">Посилання для відновлення паролю надіслано</h1>
  <img src="{% static 'img/icon/mail-box.svg' %}" class="reset__mailBox img-svg" alt="">

  <h3 class="reset__subtitle subtitle">
    Ми надіслали на вашу почтову скриньку інструкції для подальшого встановлення паролю. Перевірте будь-ласка свій e-mail, повідомлення вже чекає на вас!
  </h3>
  <h6 class="reset__text">Якщо ви не отримуєте електронного листа, переконайтесь, що ви ввели адресу, на яку зареєструвались, і перевірте папку зі спамом.</h6>
  <br/>
  <a class="reset__main" href="/">На головну</a>
</div>
{% endblock%}

src/accounts/templates/profile.html
{% extends 'base.html' %}
{% load static %}


{% block menu %}
    {% include 'includes/sidebar.html' %}
{% endblock %}

{% block header %}
    {% include 'includes/header.html' %}
{% endblock %}

{% block content %}
                <form method="POST" class="settings" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="settings__title">
                        Налаштування
                    </div>
                    <div class="settings__block">
                        <div class="settings__item">
                            <div class="settings__item--title">
                                Деталі:
                            </div>
                            {{form.errors}}
                            <div class="change">
                                <div class="change__item">
                                    <label for="">Аватар</label>
                                    <div class="change__image">
                                        <img src="{{ user.image.url }}" alt="" class="change__photo">
                                        <input type="file" class="change__edit" id="image" name="image" accept="image/*">
                                        <img class="change__delete img-svg" src="{% static 'img/icon/delete.svg' %}" alt="">
                                    </div>

                                </div>
                                <div class="change__item">
                                    <label for="">Прізвище</label>
                                    {{ form.last_name.errors }}
                                    {{ form.last_name }}
                                </div>
                                <div class="change__item">
                                    <label for="">Ім'я</label>
                                    {{ form.first_name.errors }}
                                    {{ form.first_name }}
                                </div>
                                <div class="change__item">
                                    <label for="">По-батькові</label>
                                    {{ form.surname.errors }}
                                    {{ form.surname }}
                                </div>
                            </div>
                        </div>
                        <div class="settings__item">
                            <div class="settings__item--title">
                                Інформація:
                            </div>
                            <div class="change">
                                <div class="change__item">
                                    <label for="">Логін</label>
                                    {{ form.username.errors }}
                                    {{ form.username }}
                                </div>
                                <div class="change__item">
                                    <label for="">Електронна пошта</label>
                                    {{ form.email.errors }}
                                    {{ form.email }}
                                </div>
                                <div class="change__item">
                                    <label for="">Телефон</label>
                                    {{ form.phone_number.errors }}
                                    {{ form.phone_number }}
                                </div>
                                {% if user.is_staff %}
                                <div class="change__item">
                                    <div class="change__text">
                                        Вітаємо Адміністратора
                                    </div>
                                </div>
                                {% elif not user.is_teacher %}
                                <div class="change__item">
                                    <label for="">Група</label>
                                    <div class="change__text">
                                        {% if user.in_group %}
                                        {{ user.student.group }}
                                        {% else %}
                                            Адміністратор ще не назначив Вам групу
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="change__item">
                                    <label for="">Курс</label>
                                    <div class="change__text">
                                        4
                                    </div>
                                </div>
                                <div class="change__item">
                                    <label for="">Семестр</label>
                                    <div class="change__text">
                                        8
                                    </div>
                                </div>
                                {% else %}
                                    <div class="change__item">
                                        <label>Академічна посада</label>
                                        <input type="text" name="academic_title" value="{{user.teacher.academic_title}}">
                                    </div>
                                     <div class="change__item">
                                        <label>Вчене звання</label>
                                        <input type="text" name="academic_degree" value="{{user.teacher.academic_degree}}">
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                        <div class="settings__item">
                            <div class="settings__item--title">
                                Зміна паролю:
                            </div>
                            <div class="change">
                                <a href="{% url 'accounts:password_change' %}">Змінити пароль</a>
                            </div>
                        </div>
                        <div class="settings__item">
                            <div class="settings__item--title">
                                Інше:
                            </div>
                            <div class="change">
                                <div class="change__item">
                                    <label for="">Мова</label>
                                    <select class="change__select">
                                        <option value="ukr">Українська</option>
                                        <option value="rus">Русская</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="settings__save">
                        <button class="settings__btn" type="submit">
                            <img class="img-svg" src="{% static 'img/icon/floppy-disk.svg' %}" alt="">
                            Зберегти
                        </button>
                    </div>
                </form>
{% endblock %}

src/accounts/templates/registration.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
       <section class="register">
            <div class="register__block">
                <form class="register__form" method="post">
                    <div class="register__title">
                        Реєстрація
                    </div>
                    {% csrf_token %}
                    {{form.errors}}
                    {{ form.username.errors }}
                    <div class="register__item">
                        {{form.username}}
                        <span class="register__focus">
                        </span>
                        <span class="register__item--title">
                            Логін
                        </span>
                    </div>
                    <div class="register__item">
                        {{form.first_name}}
                        <span class="register__focus">
                        </span>
                        <span class="register__item--title">
                            Ім'я
                        </span>
                    </div>
                    <div class="register__item">
                        {{form.last_name}}
                        <span class="register__focus">
                        </span>
                        <span class="register__item--title">
                            Прізвище
                        </span>
                    </div>
                    {{form.email.errors}}
                    <div class="register__item">
                        {{form.email}}
                        <span class="register__focus">
                        </span>
                        <span class="register__item--title">
                            E-mail
                        </span>
                    </div>
                    {{form.password1.errors}}
                    <div class="register__item">
                        {{form.password1}}
                        <span class="register__focus">
                        </span>
                        <span class="register__item--title">
                            Пароль
                        </span>
                    </div>
                    {{form.password2.errors}}
                    <div class="register__item">
                        {{form.password2}}
                        <span class="register__focus">
                        </span>
                        <span class="register__item--title">
                            Повторіть пароль
                        </span>
                    </div>
                    <button type="submit" class="register__btn">
                        Зареєструватися
                    </button>
                    <div class="register__text">
                        У Вас вже є аккаунт? <a href="{% url 'accounts:login' %}">Увійти</a>
                    </div>
                </form>
                {% include 'includes/captcha.html' %}
            </div>
       </section>
{% endblock %}

{% block scripts %}
    <script src="{% static 'js/auth2.js' %}"></script>
{% endblock %}