src/accounts/urls.py
from django.urls import path
from accounts.views import AccountRegistrationView, AccountLoginView, AccountLogoutView, AccountUpdateView, \
    AccountPasswordChangeView, AccountPasswordResetView, AccountPasswordResetDoneView, AccountPasswordResetConfirmView, \
    AccountPasswordResetCompleteView, AccountListView, AccountUpdateUserView

app_name = "accounts"

urlpatterns = [
    path('registration/', AccountRegistrationView.as_view(), name='registration'),
    path('login/', AccountLoginView.as_view(), name='login'),
    path('logout/', AccountLogoutView.as_view(), name='logout'),
    path('profile/', AccountUpdateView.as_view(), name='profile'),
    path('update/<int:user_id>', AccountUpdateUserView.as_view(), name='update'),
    path('password/', AccountPasswordChangeView.as_view(), name='password_change'),
    path('reset_password/', AccountPasswordResetView.as_view(),
         name='reset_password'),
    path('reset_password_sent/', AccountPasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>', AccountPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('reset_password_complete/', AccountPasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path('list/', AccountListView.as_view(), name='list'),

]

src/app/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from app.views import FirstPageView

urlpatterns = [
    path('', FirstPageView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('groups/', include('groups.urls')),
    path('lessons/', include('lessons.urls')),
    path('teachers/', include('teachers.urls')),
    path('students/', include('students.urls')),
    path('consultation/', include('consultations.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/consultations/urls.py
from django.urls import path

from consultations.views import ConsultationListView

app_name = 'consultations'

urlpatterns = [
    path('', ConsultationListView.as_view(), name='list'),
]

src/groups/urls.py
from django.urls import path, include

from groups.views import StudentJournalView, SubjectStudentJournalView, StudentGroupView, StudentListView, \
    AdminModerateGroup, JournalSelectView, TeacherJournalUpdateView, AdminModerateStudentsGroup

app_name = 'groups'

urlpatterns = [
    path('<uuid:group_uuid>/', StudentGroupView.as_view(), name='group'),
    path('moderate/', StudentListView.as_view(), name='moderate'),
    path('moderate/<uuid:group_uuid>/schedule/', AdminModerateGroup.as_view(), name='moderate_group'),
    path('moderate/<uuid:group_uuid>/students/', AdminModerateStudentsGroup.as_view(), name='moderate_group_students'),
    path('<uuid:group_uuid>/schedule/', StudentJournalView.as_view(), name='group_schedule_for_student'),
    path('<uuid:group_uuid>/journal/', StudentJournalView.as_view(), name='group_schedule_for_student'),
    path('journal/', JournalSelectView.as_view(), name='select_journal'),
    path('journal/<uuid:group_uuid>/teacher/subject/<uuid:subject_uuid>/', TeacherJournalUpdateView.as_view(),
         name='group_journal_for_teacher'),
    path('journal/<uuid:group_uuid>/student/subject/<uuid:subject_uuid>/', SubjectStudentJournalView.as_view(),
         name='subject_journal_for_student'),

]

src/teachers/urls.py
from django.urls import path

from teachers.views import TeacherDeleteView, TeacherCreateView, TeacherUpdateView, TeachersListView

app_name = 'teachers'

urlpatterns = [
    path('create/', TeacherCreateView.as_view(), name='create'),
    path('update/', TeacherUpdateView.as_view(), name='update'),
    path('delete/<int:teacher_id>', TeacherDeleteView.as_view(), name='delete'),
    path('list/', TeachersListView.as_view(), name='list'),
]

src/templates/includes/captcha.html
{% load static %}


<div class="captcha">
    <div class="cap__container">
        <div class="cap__info">
            <div class="cap__title">
                Подтвердите, что вы не являетесь роботом
            </div>
            <div class="cap__nav">
                <div class="cap__refresh">
                    <img src="{% static 'img/icon/refresh.svg' %}" class="img-svg" alt="">
                </div>
                <div class="cap__close">
                    <img src="{% static 'img/icon/close.svg' %}" class="img-svg cap__close" alt="">
                </div>
            </div>
        </div>

        <div class="cap__sign">

            <canvas id="myCanvas1" class="cap__white" width="50" height="50"></canvas>
            <canvas id="myCanvas" class="cap__include" width="50" height="50"></canvas>
            <canvas id="canvasBlurMobile" class="cap__whiteMobile" width="40" height="40"></canvas>
            <canvas id="canvasPazlMobile" class="cap__includeMobile" width="40" height="40"></canvas>
            <div class="cap__imgHide"></div>
            <div class="cap__image">
                <img class="cap__img" src="" alt="">
                <div class="cap__image--block">
                    <img src="{% static 'img/icon/loading.svg' %}" alt="" class="cap__load img-svg">
                </div>
            </div>
            <div class="cap__block">
                <div class="cap__text">
                    Потяните ползунок вправо
                </div>
                <div class="cap__square">
                    <img src="{% static 'img/icon/arrow.svg' %}" class="img-svg cap__arrow" alt="">
                    <img src="{% static 'img/icon/close.svg' %}" class="img-svg cap__no" alt="">
                    <img src="{% static 'img/icon/check.svg' %}" class="img-svg cap__check" alt="">
                </div>
            </div>
            <div class="cap__alert">
                Попробуйте еще раз, количество попыток для данного изображения: <span class="cap__alert--num"></span>
            </div>
        </div>
    </div>
</div>

src/templates/includes/header.html
{% load static %}


<header class="header">
    <div class="header__tabHide">
        <img class="img-svg" src="{% static 'img/icon/menu.svg' %}" alt="">
    </div>
    <div class="header__cath">
        Кафедра кібербезпеки та програмного забезпечення
    </div>
    {% if user.is_authenticated %}
    <div class="header__profile">
        <div class="header__item">
            <div class="header__name">
                <a href="{% url 'accounts:profile' %}">{{user.last_name}} {{user.first_name}}</a>
            </div>
            <div class="header__group">
                {% if user.is_student %}
                    {{user.student.group}}
                {% endif %}
            </div>
        </div>
        <div class="header__item header__icon">
            <img src="{{ user.image.url }}" alt="">
        </div>
        <div class="header__item">
        </div>
    </div>
    <div class="header__option">
        <a href="#" class="header__option--item">
            <img src="{% static 'img/icon/notification.svg' %}" class="img-svg" alt="">
            <span>Повідомлення</span>
        </a>
        <a href="{% url 'accounts:profile' %}" class="header__option--item">
            <img src="{% static 'img/icon/settings.svg' %}" class="img-svg" alt="">
            <span>Налаштування</span>
        </a>
        <a href="#" class="header__option--item">
            <img src="{% static 'img/icon/logout.svg' %}" class="img-svg" alt="">
            <form action="{% url 'accounts:logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit">Вихід</button>
            </form>
        </a>
    </div>
    <div class="header__menu">
        <img src="{% static 'img/icon/menu.svg' %}" class="img-svg" alt="">
    </div>
    {% else %}
    <div><a href="{% url 'accounts:registration' %}">Регистрация</a></div>
    <div><a href="{% url 'accounts:login' %}">Вход</a></div>
    {% endif %}
</header>

src/templates/includes/sidebar.html
{% load static %}

<nav class="menu">
    <div class="menu__head">
        <div class="menu__title title">
            Державний університет <br> «Одеська політехніка»
        </div>
        <img class="menu__logo" src="{% static 'img/icon/onpu.png' %}" alt="">
        <div class="menu__close">
            <img src="{% static 'img/icon/close.svg' %}" class="img-svg" alt="">
        </div>
    </div>
    <ul class="menu__list">
        {% if user.is_student %}
            {% if user.in_group %}
                <a href="{% url 'groups:group_schedule_for_student' group_uuid=user.get_group_uuid %}" class="menu__item">
                    <img src="{% static 'img/icon/calendar.svg' %}" class="img-svg" alt="">
                    <span>Розклад занять</span>
                </a>
            {% endif %}
        {% endif %}
        <a href="{% url 'consultations:list' %}" class="menu__item">
            <img src="{% static 'img/icon/calendar-time.svg' %}" class="img-svg" alt="">
            <span>Розклад консультацій</span>
        </a>
        {% if user.in_group or user.is_teacher %}
        <a href="{% if not user.is_staff %}{% url 'groups:select_journal' %}{% endif %}" class="menu__item">
            <img src="{% static 'img/icon/notebook.svg' %}" class="img-svg" alt="">
            <span>Електронний журнал</span>
        </a>
        {% endif %}
        {% if user.is_student %}
            {% if user.in_group %}
        <a href="{% url 'groups:group' group_uuid=user.get_group_uuid %}" class="menu__item">
            <img src="{% static 'img/icon/group.svg' %}" class="img-svg" alt="">
            <span>Група</span>
        </a>
            {% endif %}
        {% endif %}
        {% if user.is_staff %}
        <a href="{% url 'groups:moderate' %}" class="menu__item">
            <img src="{% static 'img/icon/teamwork.svg' %}" class="img-svg" alt="">
            <span>Налаштування груп</span>
        </a>
        {% endif %}
        {% if user.is_staff %}
        <a href="{% url 'teachers:list' %}" class="menu__item">
            <img src="{% static 'img/icon/teacher.svg' %}" class="img-svg" alt="">
            <span>Керування викладачами</span>
        </a>
        {% endif %}
        {% if user.is_authenticated %}
            <a href="{% url 'accounts:profile' %}" class="menu__item">
                <img src="{% static 'img/icon/settings.svg' %}" class="img-svg" alt="">
                <span>Налаштування профілю</span>
            </a>
        {% endif %}
    </ul>
</nav>